// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxRD0HhduaCB_edDKpZzqEawL08w_xlaM',
    appId: '1:156202833944:web:9dbb19b68685ff902b8b6d',
    messagingSenderId: '156202833944',
    projectId: 'lifease-dbaa9',
    authDomain: 'lifease-dbaa9.firebaseapp.com',
    storageBucket: 'lifease-dbaa9.firebasestorage.app',
    measurementId: 'G-MS0229WJGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD85Oie3iK-22qmfX-ipA6NtefII0ERE_o',
    appId: '1:156202833944:android:d43d18f0027ce5ca2b8b6d',
    messagingSenderId: '156202833944',
    projectId: 'lifease-dbaa9',
    storageBucket: 'lifease-dbaa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBAUSCAJ5vorAGq-h8cM4ncCCawgA1Y8Y',
    appId: '1:156202833944:ios:5a315e7f3da43d742b8b6d',
    messagingSenderId: '156202833944',
    projectId: 'lifease-dbaa9',
    storageBucket: 'lifease-dbaa9.firebasestorage.app',
    iosBundleId: 'com.example.lifease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBAUSCAJ5vorAGq-h8cM4ncCCawgA1Y8Y',
    appId: '1:156202833944:ios:5a315e7f3da43d742b8b6d',
    messagingSenderId: '156202833944',
    projectId: 'lifease-dbaa9',
    storageBucket: 'lifease-dbaa9.firebasestorage.app',
    iosBundleId: 'com.example.lifease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxRD0HhduaCB_edDKpZzqEawL08w_xlaM',
    appId: '1:156202833944:web:319ed12e90ee58a92b8b6d',
    messagingSenderId: '156202833944',
    projectId: 'lifease-dbaa9',
    authDomain: 'lifease-dbaa9.firebaseapp.com',
    storageBucket: 'lifease-dbaa9.firebasestorage.app',
    measurementId: 'G-W9Y1T72H1M',
  );
}
